language: android
install: ant debug install test
before_install:
  sudo pip install codecov
  android update project -p .
after_success:
  codecov
android:
  components:
    - platform-tools
    - tools
    - build-tools-19.1.0
    - android-19
    - sys-img-armeabi-v7a-android-19
