language: android
script: ant debug
install: android update project -p .
before_install: sudo pip install codecov
after_success: codecov
android:
  components:
    - platform-tools
    - tools
    - build-tools-19.1.0
    - android-19
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17
