language: android
install: ant deps
before_install:
  sudo pip install codecov
after_success:
  codecov
android:
  components:
    - build-tools-19.1.0
    - android-19
    - addon-google_apis-google-19
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17
